language: c
compiler: gcc

script:
  - make
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make checkdns; fi'

addons:
    apt:
        packages:
            - python3
            - autoconf
            - automake
            - autopoint
            - libtool
            - gettext
            - libidn11-dev
            - libidn2-0
            - libidn2-0-dev
            - libicu-dev
            - libunistring0
            - libunistring-dev
            - dnsutils

